# Desc
name: Unity Build Game
run-name: ${{ github.actor }} is building Game

# Event nothing
on: workflow_dispatch

# Job
jobs:
  # Testing
  test:
    # Runner
    name: Unity Testing
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          
      # Cache
      - name: Cache Assets, Packages, ProjectSettings
        uses: actions/cache@v3
        with:
          path: |
            ./Assets
            ./Packages
            ./ProjectSettings
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }} 
            
      # Unity unit testing
      - name: Unity Testing Play mode & Edit mode
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  # Building
  build:
    name: Unity Building
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - # Checkout
        - name: Checkout
          uses: actions/checkout@v3
          with:
            lfs: true

        # Cache
        - name: Cache Assets, Packages, ProjectSettings
          uses: actions/cache@v3
          with:
            path: |
              ./Assets
              ./Packages
              ./ProjectSettings
            key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      
      # Build Windows 64
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          
      # Upload to Registry
      - uses: actions/upload-artifact@v3
        with:
          name: MechAI
          path: build